[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @data/models run build",
  "pnpm --filter @app/api run build",
  "pnpm exec prisma generate --schema prisma/schema.prisma"
]

[start]
cmd = "pnpm run railway:migrate && pnpm run railway:seed && pnpm run railway:start"